import Head from "next/head";
import Link from "next/link";
import Image from "next/image";
import Search from "../components/Search";
import Tile from "../components/Tile";
import BottomMenu from "../components/BottomMenu";

export default function Home() {
  return (
    <div>
      <Head>
        <title>BeMyBee</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <div className="flex justify-end">
          <Link href="#">
            <a className="px-6 py-1 m-4 border border-transparent text-base font-medium rounded text-white bg-moon-yellow hover:bg-[#FDCA45] md:py-4 md:text-lg md:px-10">
              Sign up
            </a>
          </Link>
        </div>

        <div className="flex justify-center">
          <Image
            src="/assets/images/logo.png"
            alt="logo"
            width={270}
            height={101}
          />
        </div>

        <Search />
        <div className="grid grid-cols-2">
          <Tile icon="/assets/images/adopt_bee.svg" title="Adopt a bee" />
          <Tile icon="/assets/images/play_game.svg" title="Play a game" />
          <Tile icon="/assets/images/buy_honey.svg" title="Buy honey" />
          <Tile
            icon="/assets/images/for_beekeepers.svg"
            title="For beekeepers"
          />
        </div>

        <BottomMenu />
      </div>
    </div>
  );
}
