import Head from "next/head";
import Image from "next/image";
import Search from "../components/Search";

export default function Home() {
  return (
    <div>
      <Head>
        <title>BeMyBee</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <div className="flex justify-end">
          <a
            href="#"
            className="px-6 py-1 m-4 border border-transparent text-base font-medium rounded text-white bg-moon-yellow hover:bg-[#FDCA45] md:py-4 md:text-lg md:px-10"
          >
            Sign up
          </a>
        </div>

        <div className="flex justify-center">
          <Image
            src="/assets/images/logo.png"
            alt="logo"
            width={270}
            height={101}
          />
        </div>

        <Search />
      </div>
    </div>
  );
}
